use anyhow::Context;
use anyhow::bail;
use sqlx::any::AnyPoolOptions;
use sqlx::postgres::PgPoolOptions;
use std::env;

use crate::db::Pool;

const DATABASE_URL_ENV: &str = "CODEX_STATE_DATABASE_URL";
const SCHEMA_ENV: &str = "CODEX_STATE_SCHEMA";
const BACKEND_ENV: &str = "CODEX_STATE_BACKEND";

pub(crate) fn postgres_required() -> bool {
    env::var(BACKEND_ENV).is_ok_and(|value| value.trim().eq_ignore_ascii_case("postgres-only"))
}

pub(crate) fn configured() -> bool {
    env::var(DATABASE_URL_ENV).is_ok_and(|value| !value.trim().is_empty())
}

pub(crate) async fn open_pool() -> anyhow::Result<Pool> {
    let database_url =
        env::var(DATABASE_URL_ENV).with_context(|| format!("{DATABASE_URL_ENV} is required"))?;
    let schema = env::var(SCHEMA_ENV).with_context(|| format!("{SCHEMA_ENV} is required"))?;
    create_schema(&database_url, &schema).await?;

    sqlx::any::install_default_drivers();
    let search_path = format!("SET search_path TO \"{schema}\"");
    AnyPoolOptions::new()
        .max_connections(8)
        .after_connect(move |connection, _metadata| {
            let search_path = search_path.clone();
            Box::pin(async move {
                sqlx::raw_sql(sqlx::AssertSqlSafe(search_path))
                    .execute(connection)
                    .await?;
                Ok(())
            })
        })
        .connect(&database_url)
        .await
        .context("open Codex PostgreSQL state pool")
}

pub async fn create_schema(database_url: &str, schema: &str) -> anyhow::Result<()> {
    validate_identifier(schema)?;
    let bootstrap = PgPoolOptions::new()
        .max_connections(1)
        .connect(database_url)
        .await
        .context("connect to Codex PostgreSQL state database")?;
    let schema_sql = RUNTIME_SCHEMA_SQL.replace("{{schema}}", schema);
    sqlx::raw_sql(sqlx::AssertSqlSafe(schema_sql))
        .execute(&bootstrap)
        .await
        .with_context(|| format!("create Codex PostgreSQL runtime schema `{schema}`"))?;
    bootstrap.close().await;
    Ok(())
}

pub fn validate_identifier(value: &str) -> anyhow::Result<()> {
    let mut characters = value.chars();
    let Some(first) = characters.next() else {
        bail!("PostgreSQL schema name cannot be empty");
    };
    if !(first == '_' || first.is_ascii_alphabetic())
        || !characters.all(|character| character == '_' || character.is_ascii_alphanumeric())
    {
        bail!("invalid PostgreSQL schema name `{value}`");
    }
    Ok(())
}

const RUNTIME_SCHEMA_SQL: &str = r#"
CREATE SCHEMA IF NOT EXISTS "{{schema}}";

CREATE TABLE IF NOT EXISTS "{{schema}}".codex_schema_migrations (
    version BIGINT PRIMARY KEY,
    description TEXT NOT NULL,
    applied_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO "{{schema}}".codex_schema_migrations (version, description)
VALUES (1, 'native PostgreSQL Codex state')
ON CONFLICT (version) DO NOTHING;

CREATE TABLE IF NOT EXISTS "{{schema}}".migration_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_home TEXT NOT NULL,
    started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMPTZ,
    status TEXT NOT NULL,
    counts_json JSONB
);

CREATE TABLE IF NOT EXISTS "{{schema}}".threads (
    id TEXT PRIMARY KEY,
    rollout_path TEXT NOT NULL,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    source TEXT NOT NULL,
    model_provider TEXT NOT NULL,
    cwd TEXT NOT NULL,
    title TEXT NOT NULL,
    sandbox_policy TEXT NOT NULL,
    approval_mode TEXT NOT NULL,
    tokens_used BIGINT NOT NULL DEFAULT 0,
    has_user_event BOOLEAN NOT NULL DEFAULT FALSE,
    archived BOOLEAN NOT NULL DEFAULT FALSE,
    archived_at BIGINT,
    git_sha TEXT,
    git_branch TEXT,
    git_origin_url TEXT,
    cli_version TEXT NOT NULL DEFAULT '',
    first_user_message TEXT NOT NULL DEFAULT '',
    agent_nickname TEXT,
    agent_role TEXT,
    memory_mode TEXT NOT NULL DEFAULT 'enabled',
    model TEXT,
    reasoning_effort TEXT,
    agent_path TEXT,
    created_at_ms BIGINT,
    updated_at_ms BIGINT,
    thread_source TEXT,
    preview TEXT NOT NULL DEFAULT '',
    recency_at BIGINT NOT NULL DEFAULT 0,
    recency_at_ms BIGINT NOT NULL DEFAULT 0,
    history_mode TEXT NOT NULL DEFAULT 'legacy',
    name TEXT,
    is_pinned BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE INDEX IF NOT EXISTS idx_threads_created_at_ms
    ON "{{schema}}".threads (created_at_ms DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_threads_updated_at_ms
    ON "{{schema}}".threads (updated_at_ms DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_threads_recency_at_ms
    ON "{{schema}}".threads (recency_at_ms DESC, id DESC);

CREATE TABLE IF NOT EXISTS "{{schema}}".thread_dynamic_tools (
    thread_id TEXT NOT NULL REFERENCES "{{schema}}".threads(id) ON DELETE CASCADE,
    position BIGINT NOT NULL,
    name TEXT NOT NULL,
    description TEXT NOT NULL,
    input_schema TEXT NOT NULL,
    defer_loading BOOLEAN NOT NULL DEFAULT FALSE,
    namespace TEXT,
    PRIMARY KEY (thread_id, position)
);

CREATE TABLE IF NOT EXISTS "{{schema}}".thread_spawn_edges (
    parent_thread_id TEXT NOT NULL,
    child_thread_id TEXT PRIMARY KEY,
    status TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_thread_spawn_edges_parent_status
    ON "{{schema}}".thread_spawn_edges(parent_thread_id, status);

CREATE TABLE IF NOT EXISTS "{{schema}}".backfill_state (
    id BIGINT PRIMARY KEY,
    status TEXT NOT NULL,
    last_watermark TEXT,
    last_success_at BIGINT,
    updated_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS "{{schema}}".remote_control_enrollments (
    websocket_url TEXT NOT NULL,
    account_id TEXT NOT NULL,
    app_server_client_name TEXT NOT NULL,
    server_id TEXT NOT NULL,
    environment_id TEXT NOT NULL,
    server_name TEXT NOT NULL,
    updated_at BIGINT NOT NULL,
    remote_control_enabled BOOLEAN,
    PRIMARY KEY (websocket_url, account_id, app_server_client_name)
);

CREATE TABLE IF NOT EXISTS "{{schema}}".external_agent_config_imports (
    import_id TEXT PRIMARY KEY,
    completed_at_ms BIGINT NOT NULL,
    successes TEXT NOT NULL,
    failures TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "{{schema}}".thread_goals (
    thread_id TEXT PRIMARY KEY,
    goal_id TEXT NOT NULL,
    objective TEXT NOT NULL,
    status TEXT NOT NULL,
    token_budget BIGINT,
    tokens_used BIGINT NOT NULL DEFAULT 0,
    time_used_seconds BIGINT NOT NULL DEFAULT 0,
    created_at_ms BIGINT NOT NULL,
    updated_at_ms BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS "{{schema}}".thread_goal_continuation_deferrals (
    thread_id TEXT PRIMARY KEY REFERENCES "{{schema}}".thread_goals(thread_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "{{schema}}".stage1_outputs (
    thread_id TEXT PRIMARY KEY,
    source_updated_at BIGINT NOT NULL,
    raw_memory TEXT NOT NULL,
    rollout_summary TEXT NOT NULL,
    rollout_slug TEXT,
    generated_at BIGINT NOT NULL,
    usage_count BIGINT,
    last_usage BIGINT,
    selected_for_phase2 BOOLEAN NOT NULL DEFAULT FALSE,
    selected_for_phase2_source_updated_at BIGINT
);
CREATE INDEX IF NOT EXISTS idx_stage1_outputs_source_updated_at
    ON "{{schema}}".stage1_outputs(source_updated_at DESC);

CREATE TABLE IF NOT EXISTS "{{schema}}".jobs (
    kind TEXT NOT NULL,
    job_key TEXT NOT NULL,
    status TEXT NOT NULL,
    worker_id TEXT,
    ownership_token TEXT,
    started_at BIGINT,
    finished_at BIGINT,
    lease_until BIGINT,
    retry_at BIGINT,
    retry_remaining BIGINT NOT NULL,
    last_error TEXT,
    input_watermark BIGINT,
    last_success_watermark BIGINT,
    PRIMARY KEY (kind, job_key)
);
CREATE INDEX IF NOT EXISTS idx_jobs_kind_status_retry_lease
    ON "{{schema}}".jobs(kind, status, retry_at, lease_until);

CREATE TABLE IF NOT EXISTS "{{schema}}".logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts BIGINT NOT NULL,
    ts_nanos BIGINT NOT NULL,
    level TEXT NOT NULL,
    target TEXT NOT NULL,
    feedback_log_body TEXT,
    module_path TEXT,
    file TEXT,
    line BIGINT,
    thread_id TEXT,
    process_uuid TEXT,
    estimated_bytes BIGINT NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_logs_ts
    ON "{{schema}}".logs(ts DESC, ts_nanos DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_logs_thread_id_ts
    ON "{{schema}}".logs(thread_id, ts DESC, ts_nanos DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_logs_process_uuid_threadless_ts
    ON "{{schema}}".logs(process_uuid, ts DESC, ts_nanos DESC, id DESC)
    WHERE thread_id IS NULL;

CREATE TABLE IF NOT EXISTS "{{schema}}".thread_turns (
    thread_id TEXT NOT NULL,
    turn_id TEXT NOT NULL,
    rollout_ordinal BIGINT NOT NULL,
    status TEXT NOT NULL,
    error_json TEXT,
    started_at BIGINT,
    completed_at BIGINT,
    duration_ms BIGINT,
    first_user_item_id TEXT,
    final_agent_item_id TEXT,
    rollout_byte_offset BIGINT,
    rollout_end_ordinal BIGINT,
    rollout_end_byte_offset BIGINT,
    PRIMARY KEY (thread_id, turn_id)
);

CREATE TABLE IF NOT EXISTS "{{schema}}".thread_items (
    thread_id TEXT NOT NULL,
    turn_id TEXT NOT NULL,
    item_id TEXT NOT NULL,
    rollout_ordinal BIGINT NOT NULL,
    updated_at_ordinal BIGINT NOT NULL DEFAULT 0,
    created_at_ms BIGINT NOT NULL,
    item_json TEXT NOT NULL,
    item_type TEXT NOT NULL DEFAULT '',
    PRIMARY KEY (thread_id, turn_id, item_id)
);
CREATE INDEX IF NOT EXISTS idx_thread_items_by_turn_page
    ON "{{schema}}".thread_items(thread_id, turn_id, rollout_ordinal);
CREATE INDEX IF NOT EXISTS idx_thread_items_by_update
    ON "{{schema}}".thread_items(thread_id, updated_at_ordinal);
CREATE INDEX IF NOT EXISTS idx_thread_items_by_turn_update
    ON "{{schema}}".thread_items(thread_id, turn_id, updated_at_ordinal);
CREATE INDEX IF NOT EXISTS idx_thread_items_user_messages
    ON "{{schema}}".thread_items(thread_id, item_type, rollout_ordinal);

CREATE TABLE IF NOT EXISTS "{{schema}}".thread_history_projection_state (
    thread_id TEXT PRIMARY KEY,
    next_rollout_byte_offset BIGINT NOT NULL,
    next_rollout_ordinal BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS "{{schema}}".thread_rollout_events (
    thread_id TEXT NOT NULL,
    rollout_ordinal BIGINT NOT NULL,
    rollout_byte_offset BIGINT NOT NULL,
    rollout_end_byte_offset BIGINT NOT NULL,
    created_at_ms BIGINT NOT NULL,
    line_type TEXT NOT NULL,
    payload_type TEXT,
    raw_json JSONB NOT NULL,
    PRIMARY KEY (thread_id, rollout_ordinal)
);
CREATE INDEX IF NOT EXISTS thread_rollout_events_type_idx
    ON "{{schema}}".thread_rollout_events(thread_id, line_type, payload_type, rollout_ordinal);

-- These tables existed in older Codex state databases. Current Codex no
-- longer executes jobs from them, but migration preserves every source row.
CREATE TABLE IF NOT EXISTS "{{schema}}".legacy_agent_jobs (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    status TEXT NOT NULL,
    instruction TEXT NOT NULL,
    output_schema_json TEXT,
    input_headers_json TEXT NOT NULL,
    input_csv_path TEXT NOT NULL,
    output_csv_path TEXT NOT NULL,
    auto_export BOOLEAN NOT NULL DEFAULT TRUE,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    started_at BIGINT,
    completed_at BIGINT,
    last_error TEXT,
    max_runtime_seconds BIGINT
);

CREATE TABLE IF NOT EXISTS "{{schema}}".legacy_agent_job_items (
    job_id TEXT NOT NULL REFERENCES "{{schema}}".legacy_agent_jobs(id) ON DELETE CASCADE,
    item_id TEXT NOT NULL,
    row_index BIGINT NOT NULL,
    source_id TEXT,
    row_json TEXT NOT NULL,
    status TEXT NOT NULL,
    assigned_thread_id TEXT,
    attempt_count BIGINT NOT NULL DEFAULT 0,
    result_json TEXT,
    last_error TEXT,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    completed_at BIGINT,
    reported_at BIGINT,
    PRIMARY KEY (job_id, item_id)
);
"#;
